/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/adverts` | `/adverts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/inventory-import` | `/inventory-import`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/medications` | `/medications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/adverts` | `/adverts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/inventory-import` | `/inventory-import`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/inventory` | `/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/medications` | `/medications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/adverts${`?${string}` | `#${string}` | ''}` | `/adverts${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/inventory-import${`?${string}` | `#${string}` | ''}` | `/inventory-import${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/inventory${`?${string}` | `#${string}` | ''}` | `/inventory${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(user)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/medications${`?${string}` | `#${string}` | ''}` | `/medications${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/adverts` | `/adverts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/inventory-import` | `/inventory-import`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/medications` | `/medications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
